[phases.setup]
# Ensure Node 18 and npm 9 are used (matches Railway defaults)
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["CI=false npm run build"]

[phases.start]
cmd = "serve -s build -l ${PORT}"
